### ISSUE TITLE
Use project.json instead

### ISSUE THREAD

**Issue by AArnott** [vbfox/PInvoke.Forms.Test#1]
What do you think of using project.json in this project instead of packages.config? It would look simpler (especially as it's a sample) since it wouldn't have to show the transitive closure of all package dependencies.

**Comment by AArnott** [comment]
BTW, I'm willing to submit the PR if you're willing.

**Comment by vbfox** [comment]
If you want to PR it no problem, i'll accept it.

I'm personally staying away from `project.json` on most projects as my normal tool chain is FAKE + Paket (I find paket a lot more usable that project.json, especially the concept of lock file is really useful, and having whole solution dependencies declared in a single place is great)

Still, I didn't intend to convert this project to paket and project.json would be a lot better than packages.config so :+1: for the PR.
